env:
  global:
    - secure: e5yjrK14l6mHxMIZ/YJnv7Q2ceYfJPUdxjL470utRgl2YFHBjZICoXi0yCETAzJPkbjbsjjGB0c3Ea99zcSjb4bDut82z62KfmnqleseeGSjDzO5dYzRe/g46CtulHTld6aJR94/ggOp9dOKhKZBxgTooc7SDeyA6oZCqUCq7tU4F5luBllJCXLTUX3fHBP6AdlP6JveF9LKEdxUXvDX/eI0WW8q7Dp4+5FKvmt0Wp3YAEnEQm6SAD0MN6kE5JXCpRzVM4bPaN5CyQXtt4ZrwyM+eolJsyuYxNCD4jiIsucvbGa6ET6Awif2OXNGkQYVczE4YEnVsxUQfDJHC9PUOYDtFCkTHApflCJFD66kW/eCnRmmJYRqF4+shFt0LqB2VA7aQokx9AAopuLSGW1gBpF3ZsowFMJPSZC+bcKIGqySHk5/KIwrCdyNmIcymyzSIiVNH0peVTI3AfoAfYH8OFD80RDt9zzOgnI8Zm20ry/SzH2s5DoMxIOWcyUzOb1DAjpN4v7RlDNFI5ZgHZgBEtLSNiQtZT0z/S6FZaA0Ogon+YPK/t8bY2b07Uz58MGOFMgFRwMSl4d/yG+PNcK+oibXBjy0LdR3JTotsIaqYNR/g1hxK91p6kR2HNKcnaR4ejHq1Eex6bkZFeJ7WssvhFNRDmF/5gLxvc2XelzqLF4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Phishing.Database
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
