env:
  global:
    - secure: T63gNpVowWwNzQKge8Rn6WufHXmdQEukRHd67PUmdWbNKJ1PsvOVpXGh0K8iuMDPxSANgcrrENOnuXNxDn3Nho0DeiLFKk/buce1b7xb/fUxiEYyLZExa2pEu8yAhPmwltUkBsefxAkmmsS09tmdS5UosQ3KOjcgKDucVd+mb7M8q3HI0z2nCpkejYfnQtZvLMzIULNftRLYbHuMpG/T3OPII5FvxrBYEXPoTM/S3eDDtq/dvu64KSJY+nM6z+6HuBaGthG5DrOlHbQHgL89Pbj4NqFdS7xATVxM2cd+iFFy9GRrnsLqXBPc2qksbEp29jzL6lJrTVOCTYwztizes/2I6600RBOpwhXko3/qqqwcpHnIzhx/M2QYFIPmHttZMUaHL8BO9IGyGRdkN7VciCu1piArGypnGslQSoPwMpUaUua1BRxmqV/yMZAs4N+FHstS6iE1onGKqp4bRKGC4GFeqLf1N5X+Bd6ylbzcpSw6OHbcZ7Rj8KeD5LpukvKfYFgAI3g+0lzR3c9iD9iBtdhlXfNWFaSH+xsvoU23JyptOQ6iBaeyJhp4gMv0zADPyywnHOlRifckWUyOWF1zumZbYlPmDSUnLYcxRx1ZlflMwQYrNfjuU0oIueFVuW1yHHLN/IdBX4CpXETmiwY6h8pU3ADnrHe6HqVkccfpjvw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Phishing.Database
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
