env:
  global:
    - secure: StNY8sT9988Ew92wW3QAUnQcSA7+SkkWdPcKDi8v3DtRI/adVC4oVS7DzFYxPN5tpQfZljJ23WN2oWg9GNcFfkZ9hQkceHLMnl7Y4NPbgp169AmGTNqOfbsprHRbU+ps5kI7kr+fRhZJJyq66ivdpiLwlO+T6+KxWg6uf+1RgdmcIfEd+clS3iW5wKC/1b+e784bxyx9rj+SlSvzTjxy2Y5HmTolBciv8foKzO6WnNLZy3pJWA70u22NucUZJJRPZ2+Xte9/H24ksNOP/IPKlvGrX3CTQBVWaC5tFmBVUuWOTfwBiXgmWVSD3eEMtBmohlXTUvMb3aw8mHf+OGk07ODguF2ZSMRr68a6FVd4iCkVQQ1vODHoNseCJrwhZD2C7qeeLRK1D7DE5oVPpsnl5VyfLgfisbJEmyI0u/wWdmSwvW8hIkrmmq/mHDc4eLRoAiALfz2lgzJdKJGf8C3L/x2QQMhgzAwJUAp5QPzua8DS2ml298gJGePT3gQ5KhjWgiGljY5Q6W3LfU56pic+VrPclWHn/uuZa+Z8MX4BjyNCTQ9Kb3pAueKJpTQKK83jYEmfC5yIcN3vHajjfxq8GI+oB32eyuDeHDZKjhb+YLIT5d2R4+BecOIPb6/+a8B9Sdj3NS/J4tgfwk2s7YzoRcExClg6Hgz+pfKNRiSanUQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Phishing.Database
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
